spring:
  datasource:
    #url: jdbc:mysql://localhost:3306/preachblog
    #url: jdbc:mysql://awseb-e-fsxvpkcw3i-stack-awsebrdsdatabase-ffq2plibi5uj.c8wrveuy7div.us-west-2.rds.amazonaws.com:3306/sys?useUnicode=true&useJDBCCompliantTimezone
    url: jdbc:mysql://edbd.c8wrveuy7div.us-west-2.rds.amazonaws.com:3306/ebdb?useUnicode=true&useJDBCCompliantTimezone
    username: root
    password: password
  jpa:
    hibernate:
      ddl-auto: create-drop 
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl 
    show-sql: true
    database: mysql
    open-in-view: true
    #local Database
    #url: jdbc:mysql://localhost:3306/preachblog
    #username: root
    #password: rootroot
  main:  
    allow-circular-references: true
  
  


